ikaros:
  migration:
    enable: false
    r2dbc:
      # r2dbc:pool:postgresql://<host>:<port>/<database>
      url: r2dbc:pool:postgresql://localhost:5432/newikaros
      username: ikaros
      password: openikaros